name: ODS Jenkins Library Build

on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: check the value of github.workspace and runner.temp
              run: |
                echo "github.workspace = ${{ github.workspace }}"
                echo "runner.temp = ${{ runner.temp }}"

            - name: Set up OpenJDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '11'
                check-latest: true

            - name: Cache
              uses: actions/cache@v3
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Clean build directory
              run: rm -rf build

            - name: Build with Gradle
              run: ./gradlew -Djava.io.tmpdir=${{ runner.temp }} clean build
              env:
                  NO_NEXUS: true

            - name: Check docs are up-to-date
              run: |
                ./.github/workflows/check-docs.sh
              env:
                  NO_NEXUS: true

            - name: CodeNarc Report
              uses: actions/upload-artifact@v4
              if: ${{ always() }}
              with:
                  name: CodeNarc Report
                  path: build/reports/codenarc/main.html

            - name: Test Report
              uses: actions/upload-artifact@v4
              if: ${{ always() }}
              with:
                  name: Test Report
                  path: build/reports/tests/test/
